---
author: 'Chris Williams <chris@bingosnet.co.uk>'
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Acme-POE-Acronym-Generator
no_index:
  directory:
    - inc
    - t
requires:
  Math::Random: 0.69
version: 1.01
